#!/bin/sh

lwiki_base="$(cd $(dirname "$0");pwd)"

if test -z "$1"; then
  echo 'lwiki: directory is not specified!' >&2
  echo 'usage: lwiki-init <directory>' >&2
  exit 1
fi

if test -e "$1"; then
  echo 'lwiki: specified directory already exists!' >&2
  exit 1
fi

mkdir -p "$1"
cd "$1"

mkdir -p .data .lock
chmod 775 .data .lock
sudo chown :apache .data .lock
ln -s "$lwiki_base/res" res
ln -s "$lwiki_base/lib" .lib
ln -s "$lwiki_base/index.php" index.php
