#!/bin/bash

#------------------------------------------------------------------------------
# from mshex/functions/hdirname.sh

function hdirname/readlink {
  local path="$1"
  case "$OSTYPE" in
  (cygwin|linux-gnu)
    PATH=/bin:/usr/bin readlink -f "$path" ;;
  (darwin*|*)
    local PWD="$PWD" OLDPWD="$OLDPWD"
    while [[ -h $path ]]; do
      local link="$(PATH=/bin:/usr/bin readlink "$path" || true)"
      [[ $link ]] || break

      if [[ $link = /* || $path != */* ]]; then
        path="$link"
      else
        local dir="${path%/*}"
        path="${dir%/}/$link"
      fi
    done
    echo -n "$path" ;;
  esac
}

function hdirname {
  if [[ $1 == -v ]]; then
    eval '
      '$2'="$3"
      [[ -h ${'$2'} ]] && '$2'=$(hdirname/readlink "${'$2'}")

      if [[ ${'$2'} == */* ]]; then
        '$2'="${'$2'%/*}"
        : "${'$2':=/}"
      else
        '$2'="${4-$PWD}"
      fi
    '
  elif [[ $1 == -v* ]]; then
    hdirname -v "${1:2}" "${@:2}"
  else
    local ret
    hdirname -v ret "$@"
    echo -n "$ret"
  fi
}
#------------------------------------------------------------------------------

hdirname -v LWIKIPATH "$0"

function convert {
  local file=
  local opt_error=
  local opt_header=
  local opt_aghbase=http://tkynt2.phys.s.u-tokyo.ac.jp/~murase/agh
  while (($#)); do
    local arg="$1"
    shift
    case "$arg" in
    (--header) opt_header=1 ;;
    (--aghbase=*) opt_aghbase=${arg#*=} ;;
    (-*)
      opt_error=1
      echo "${0##*/} (arg $arg): an unrecognized option." >&2 ;;
    (*)
      if [[ $file ]]; then
        opt_error=1
        echo "${0##*/} (arg $arg): multiple files cannot be specified." >&2
      fi

      if [[ ! -e $arg ]]; then
        opt_error=1
        echo "${0##*/} (arg $arg): the specified file does not exist." >&2
      elif [[ ! -f $arg ]]; then
        opt_error=1
        echo "${0##*/} (arg $arg): the specified file is not an ordinary file." >&2
      else
        file="$arg"
      fi ;;
    esac
  done

  if [[ ! $file ]]; then
    opt_error=1
    echo "${0##*/} (arg $arg): an input file is not specified." >&2
  fi

  [[ $opt_error ]] && return 1

  if [[ $opt_header ]]; then
    printf '<html><head><meta name="agh-fly-type" content="color,tex" /><script src="%s/agh.fly.js"></script></head>\n' "$opt_aghbase"
    printf '<body>'
  fi

  php "$LWIKIPATH/lwiki-convert" "$file"

  if [[ $opt_header ]]; then
    echo '</body></html>'
  fi
}

function command.view {
  convert "$@" | w3m -T text/html
}

# function command.links {
#   ftmp="$(mktemp XXXXXXXXXX.htm)"
#   convert "$@" > "$ftmp"
#   links  -html-assume-codepage utf-8 "$ftmp"
#   rm -f "$ftmp"
# }

function command.convert {
  convert "$@"
}


function command.init {
  local base=$(cd -P $LWIKIPATH; echo -n $PWD)

  if [[ -d .data && -d .lock && -d res && -h index.php && -h .lib ]]; then
    echo "lwiki-init: Updating old type lwiki directory..."
    mkdir .lwiki
    mv .data .lwiki/data
    mv .lock .lwiki/lock
    mv .lib .lwiki/lib
    echo "lwiki-init: done"
    return 0
  fi

  if [[ -d .lwiki ]]; then
    echo "lwiki-init: The subdirectory \`.lwiki' already exists!" >&2
    echo "lwiki-init: This directory may be already a lwiki directory." >&2
    echo "lwiki-init: Failed to initialize the lwiki directory." >&2
    return 1
  fi

  if [[ -e index.php || -e res ]]; then
    echo "lwiki-init: The file index.php or res already exists!" >&2
    echo "lwiki-init: Failed to initialize the lwiki directory." >&2
    return 1
  fi

  mkdir -p .lwiki/data .lwiki/lock
  ln -s "$base/res" res
  ln -s "$base/lib" .lwiki/lib
  ln -s "$base/index.php" index.php
  cp "$base/lwiki_config.php" lwiki_config.php

  echo "lwiki-init: changing owner group of .lwiki/data and .lwiki/lock to \`apache'..."
  chmod 775 .lwiki/data .lwiki/lock
  sudo chown :apache .lwiki/data .lwiki/lock
  sudo chcon -R -t httpd_sys_rw_content_t .lwiki/lock .lwiki/data
  echo "lwiki-init: done"
}

function command.archive {
  if [[ ! -d .lwiki ]]; then
    echo "lwiki-save: this is not a lwiki directory." >&2
    return 1
  fi

  (
    cd .lwiki/data
    tar caf ../../"${1:-data}".$(date +%Y%m%d).tar.xz *
  )
}

function command.page-convert {
  if [[ ! -d .lwiki ]]; then
    echo "lwiki.page-convert: this is not a lwiki directory" >&2
    return 1
  fi

  local pageid
  local fError=
  local -a pageids
  pageids=()
  if (($#)); then
    for pageid in "$@"; do
      if [[ ! -f .lwiki/data/page.$pageid.wiki ]]; then
        echo "lwiki.page-convert: the specified page, pageid=$pageid, is not found." >&2
        fError=1
        continue
      fi
      pageids+=("$pageid")
    done
  else
    local page
    for page in .lwiki/data/page.*.wiki; do
      pageid="${page#.lwiki/data/page.}"
      pageid="${pageid%.wiki}"
      pageids+=("$pageid")
    done
  fi

  [[ $fError ]] && return 1

  for pageid in "${pageids[@]}"; do
    echo "$pageid"
    php "$LWIKIPATH"/lwiki-page-convert.php "$pageid"
  done
}

if [[ ! $1 ]]; then
  echo "lwiki: operation not specified" >&2
  exit 1
fi
name="$1"
shift 1

if ! declare -f "command.$name" &> /dev/null; then
  echo "lwiki: unrecognized operation: '$name'" >&2
  exit 1
fi

"command.$name" "$@"
